### ISSUE TITLE
git submodule update error

### ISSUE THREAD

**Issue by dimpol** [JackOfMostTrades/bluebox#1]
I am trying to replicate the attack on my lab. git submodule update results in the following error...

error: no such remote ref 644f8aab1337b971a144b047b418a75fa32a78ff
Fetched in submodule path 'evil_dc/dns/dnslib', but it did not contain 644f8aab1337b971a144b047b418a75fa32a78ff. Direct fetching of that commit failed.

Any idea to resolve this?

**Comment by JackOfMostTrades** [comment]
It looks like the [upstream project](https://github.com/paulchakravarti/dnslib) I was depending on removed the particular revision I had checked out from their git history. But just updating to the latest HEAD revision seems to have worked, so go ahead and try doing `git pull` to get the latest from bluebox, and then do `git submodule init` and `git submodule update` again.

Let me know if you're able to get things working!

**Comment by dimpol** [comment]
Thanks a lot for pointing me to the right direction. Great work on bluebox! Closing the issue....
